name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- DEPENDENCIES UTAMA ---
  # 1. State Management (Otak Aplikasi)
  provider: ^6.1.5
  
  # 3. Database Lokal (Simpan Riwayat)
  sqflite: ^2.4.2
  path: ^1.9.1
  
  # 4. Format Tanggal & Waktu
  intl: ^0.19.0
  
  # 5. Izin Android (Bluetooth/Lokasi)
  permission_handler: ^11.3.0

  # 6. Ikon Bawaan
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# --- KONFIGURASI FLUTTER ---
flutter:
  uses-material-design: true

  # --- PENDAFTARAN ASET ---
  # Mas pakai tanda garis miring (/) di akhir.
  # Artinya: "Tolong ambil SEMUA file gambar di dalam folder assets"
  assets:
    - assets/